server:
  port: 8083

spring:
  application:
    name: presence-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/chat_server_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Nn3832143
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false # Tắt log SQL cho đỡ rối màn hình