server:
  port: 8090

spring:
  application:
    name: user-profile-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/chat_profile_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update