server:
  port: 8090

spring:
  application:
    name: user-profile-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/chat_profile_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    show-sql: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus, health
    metrics:
      tags:
        application: ${spring.application.name}