server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Dịch vụ Xác thực & Cấp token
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**

            # Dịch vụ Nhắn tin thời gian thực (Websocket)
            - id: messaging-ws
              uri: ws://messaging-ws:8082
              predicates:
                - Path=/ws/chat/**

            # Dịch vụ Theo dõi trạng thái Online/Offline
            - id: presence-service
              uri: http://presence-service:8083
              predicates:
                - Path=/api/presence/**

            # Dịch vụ Quản lý lịch sử hệ thống (Log)
            - id: log-service
              uri: http://log-service:8084
              predicates:
                - Path=/api/logs/**

            # Dịch vụ Thông báo (Notification)
            - id: notification-service
              uri: http://notification-service:8088
              predicates:
                - Path=/api/notifications/**,/api/channels/*/ack

            # Dịch vụ Quản lý File
            - id: file-service
              uri: http://file-service:8089
              predicates:
                - Path=/api/files/**